"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-05-29

Initial Skoll schema (issue phase-1.15). Mirrors ``db/schema.sql`` 1:1. Autogenerated from
``skoll.db.models`` then hand-verified against the canonical DDL; two hand-edits were applied
that autogenerate cannot produce:
  * the ``idx_sessions_updated`` expression index (``updated_at DESC``) — SQLite cannot
    reflect expression indexes, so Alembic skips it on autogenerate;
  * the ``schema_meta`` seed rows (``schema_version`` / ``created_at``) from schema.sql.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('approval_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('tool_call_id', sa.Text(), nullable=False),
    sa.Column('tool_name', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('edited_args', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.CheckConstraint("action IN ('approved', 'rejected', 'edited_and_approved', 'auto_approved')", name='ck_approval_log_action'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_log', schema=None) as batch_op:
        batch_op.create_index('idx_approval_session', ['session_id', 'occurred_at'], unique=False)

    op.create_table('preflight_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('tool_call_id', sa.Text(), nullable=True),
    sa.Column('check_name', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.CheckConstraint("result IN ('pass', 'fail')", name='ck_preflight_log_result'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('preflight_log', schema=None) as batch_op:
        batch_op.create_index('idx_preflight_session', ['session_id', 'occurred_at'], unique=False)

    op.create_table('schema_meta',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('root_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('last_opened_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('root_path')
    )
    op.create_table('index_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('progress', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('files_total', sa.Integer(), nullable=True),
    sa.Column('files_indexed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.CheckConstraint("state IN ('queued', 'running', 'completed', 'failed')", name='ck_index_jobs_state'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rag_chunks', schema=None) as batch_op:
        batch_op.create_index('idx_rag_file_hash', ['workspace_id', 'file_hash'], unique=False)
        batch_op.create_index('idx_rag_workspace_file', ['workspace_id', 'file_path'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('system_prompt_overrides', sa.Text(), nullable=True),
    sa.Column('auto_approve', sa.Text(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('last_iteration', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('state', sa.Text(), server_default=sa.text("'idle'"), nullable=False),
    sa.CheckConstraint("state IN ('idle', 'running', 'error', 'completed')", name='ck_sessions_state'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('idx_sessions_workspace', ['workspace_id'], unique=False)
    # Expression index (updated_at DESC) — hand-added; autogenerate cannot emit it.
    op.create_index('idx_sessions_updated', 'sessions', [sa.text('updated_at DESC')])

    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_call_id', sa.Text(), nullable=True),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.CheckConstraint("role IN ('system', 'user', 'assistant', 'tool')", name='ck_messages_role'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_messages_session', ['session_id', 'created_at'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.CheckConstraint("kind IN ('file', 'image', 'url')", name='ck_attachments_kind'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index('idx_attachments_session', ['session_id'], unique=False)

    op.create_table('tool_calls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('arguments', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('requires_approval', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.Text(), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.CheckConstraint("status IN ('pending_args', 'ready', 'awaiting_approval', 'approved', 'rejected', 'executing', 'completed', 'failed')", name='ck_tool_calls_status'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.create_index('idx_toolcalls_session', ['session_id', 'created_at'], unique=False)
        batch_op.create_index('idx_toolcalls_status', ['status'], unique=False, sqlite_where=sa.text("status IN ('awaiting_approval', 'executing')"))

    # Seed schema_meta to mirror the INSERTs in db/schema.sql.
    op.execute(
        "INSERT OR REPLACE INTO schema_meta(key, value) VALUES ('schema_version', '1')"
    )
    op.execute(
        "INSERT OR REPLACE INTO schema_meta(key, value) "
        "VALUES ('created_at', datetime('now'))"
    )


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.drop_index('idx_toolcalls_status', sqlite_where=sa.text("status IN ('awaiting_approval', 'executing')"))
        batch_op.drop_index('idx_toolcalls_session')

    op.drop_table('tool_calls')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index('idx_attachments_session')

    op.drop_table('attachments')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('idx_messages_session')

    op.drop_table('messages')
    op.drop_index('idx_sessions_updated', table_name='sessions')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_sessions_workspace')

    op.drop_table('sessions')
    with op.batch_alter_table('rag_chunks', schema=None) as batch_op:
        batch_op.drop_index('idx_rag_workspace_file')
        batch_op.drop_index('idx_rag_file_hash')

    op.drop_table('rag_chunks')
    op.drop_table('index_jobs')
    op.drop_table('workspaces')
    op.drop_table('schema_meta')
    with op.batch_alter_table('preflight_log', schema=None) as batch_op:
        batch_op.drop_index('idx_preflight_session')

    op.drop_table('preflight_log')
    with op.batch_alter_table('approval_log', schema=None) as batch_op:
        batch_op.drop_index('idx_approval_session')

    op.drop_table('approval_log')
